//Chemistry-Reagents-Core.dm

/datum/reagent/blood
	name = "Кровь"
	taste_description = "железа"
	rugender = "female"
	ncase = "кровь"
	gcase = "крови"
	dcase = "крови"
	acase = "кровь"
	icase = "кровью"
	pcase = "крови"
	glass_name = "Томатный сок"
	glass_desc = "А это точно сок?"
	glass_ncase = "томатный сок"
	glass_gcase = "томатного сока"
	glass_dcase = "томатному соку"
	glass_acase = "томатный сок"
	glass_icase = "томатным соком"
	glass_pcase = "томатном соке"
	glass_rugender = "male"

/datum/reagent/blood/synthblood
	name = "Синтетическая кровь"
	rugender = "female"
	ncase = "синтетическая кровь"
	gcase = "синтетической крови"
	dcase = "синтетической крови"
	acase = "синтетическую кровь"
	icase = "синтетической кровью"
	pcase = "синтетической крови"

/datum/reagent/blood/synthblood/dilute
	name = "Синтетическая плазма"
	rugender = "female"
	ncase = "синтетическая плазма"
	gcase = "синтетической плазмы"
	dcase = "синтетической плазме"
	acase = "синтетическую плазму"
	icase = "синтетической плазмой"
	pcase = "синтетической плазме"

/datum/reagent/antibodies
	name = "Антитела"
	taste_description = "слизи"
	rugender = "plural"
	ncase = "антитела"
	gcase = "антител"
	dcase = "антителам"
	acase = "антитела"
	icase = "антителами"
	pcase = "антителах"

/datum/reagent/water
	name = "Вода"
	taste_description = "воды"
	description = "Распространённая жидкая субстанция, состоящая из водорода и кислорода."
	ncase = "вода"
	gcase = "воды"
	dcase = "воде"
	acase = "воду"
	icase = "водой"
	pcase = "воде"
	rugender = "female"
	glass_name = "Вода"
	glass_desc = "Мать всех освежающих напитков."
	glass_ncase = "вода"
	glass_gcase = "воды"
	glass_dcase = "воде"
	glass_acase = "воду"
	glass_icase = "водой"
	glass_pcase = "воде"
	glass_rugender = "female"

/datum/reagent/fuel
	name = "Сварочное топливо"
	description = "Горючее, необходимое для сварки."
	taste_description = "противного металла"
	rugender = "neuter"
	ncase = "сварочное топливо"
	gcase = "сварочного топлива"
	dcase = "сварочному топливу"
	acase = "сварочное топливо"
	icase = "сварочным топливом"
	pcase = "сварочном топливе"
	glass_name = "Сварочное топливо"
	glass_desc = "Если Вы не являетесь сварочным инструментом, то употреблять это, пожалуй, не стоит."
	glass_rugender = "neuter"
	glass_ncase = "сварочное топливо"
	glass_gcase = "сварочного топлива"
	glass_dcase = "сварочному топливу"
	glass_acase = "сварочное топливо"
	glass_icase = "сварочным топливом"
	glass_pcase = "сварочном топливе"

//Chemistry-Reagents-Dispenser.dm

/datum/reagent/aluminum
	name = "Алюминий"
	description = "Металл подгруппы бора серебристого цвета."
	taste_description = "металла"
	rugender = "male"
	ncase = "алюминий "
	gcase = "алюминия"
	dcase = "алюминию"
	acase = "алюминий "
	icase = "алюминием"
	pcase = "алюминии"

/datum/reagent/calcium
	name = "Кальций"
	description = "Химический элемент, важнейший в составе костей."
	taste_description = "металлического мела"
	rugender = "male"
	ncase = "кальций "
	gcase = "кальция"
	dcase = "кальцию"
	acase = "кальций "
	icase = "кальцием"
	pcase = "кальции"

/datum/reagent/carbon
	name = "Углерод"
	description = "Химический элемент, из которого состоит всё живое."
	taste_description = "кислого мела"
	rugender = "male"
	ncase = "углерод"
	gcase = "углерода"
	dcase = "углероду"
	acase = "углерод"
	icase = "углеродом"
	pcase = "углероде"

/datum/reagent/chlorine
	name = "Хлор"
	description = "Химический элемент с узнаваемым запахом."
	taste_description = "воды из бассейна"
	rugender = "male"
	ncase = "хлор"
	gcase = "хлора"
	dcase = "хлору"
	acase = "хлор"
	icase = "хлором"
	pcase = "хлоре"

/datum/reagent/copper
	name = "Медь"
	description = "Металл-проводник."
	taste_description = "копейки"
	rugender = "female"
	ncase = "медь"
	gcase = "меди"
	dcase = "меди"
	acase = "медь"
	icase = "медью"
	pcase = "меди"

/datum/reagent/ethanol
	name = "Этанол"
	description = "Распространённый спирт с множеством применений."
	taste_description = "чистого спирта"
	rugender = "male"
	ncase = "этанол"
	gcase = "этанола"
	dcase = "этанолу"
	acase = "этанол"
	icase = "этанолом"
	pcase = "этаноле"
	glass_name = "Этанол"
	glass_desc = "Распространённый спирт с множеством применений."
	glass_rugender = "male"
	glass_ncase = "этанол"
	glass_gcase = "этанола"
	glass_dcase = "этанолу"
	glass_acase = "этанол"
	glass_icase = "этанолом"
	glass_pcase = "этаноле"

/datum/reagent/fluorine
	name = "Фтор"
	description = "Активный химический элемент."
	taste_description = "кислоты"
	rugender = "male"
	ncase = "фтор"
	gcase = "фтора"
	dcase = "фтору"
	acase = "фтор"
	icase = "фтором"
	pcase = "фторе"

/datum/reagent/hydrogen
	name = "Водород"
	description = "Горючий двухатомный газ без цвета, вкуса и запаха."
	rugender = "male"
	ncase = "водород"
	gcase = "водорода"
	dcase = "водороду"
	acase = "водород"
	icase = "водородом"
	pcase = "водороде"

/datum/reagent/iron
	name = "Железо"
	description = "Чистый металл."
	taste_description = "металла"
	rugender = "neuter"
	ncase = "железо"
	gcase = "железа"
	dcase = "железу"
	acase = "железо"
	icase = "железом"
	pcase = "железе"

/datum/reagent/lithium
	name = "Литий"
	description = "Химический элемент, используемый в качестве антидепрессанта."
	taste_description = "металла"
	rugender = "male"
	ncase = "литий "
	gcase = "лития"
	dcase = "литию"
	acase = "литий "
	icase = "литием"
	pcase = "литии"

/datum/reagent/mercury
	name = "Ртуть"
	description = "Химический элемент."
	rugender = "female"
	ncase = "ртуть"
	gcase = "ртути"
	dcase = "ртути"
	acase = "ртуть"
	icase = "ртутью"
	pcase = "ртути"

/datum/reagent/nitrogen
	name = "Азот"
	description = "Газ без цвета, запаха и вкуса."
	rugender = "male"
	ncase = "азот"
	gcase = "азота"
	dcase = "азоту"
	acase = "азот"
	icase = "азотом"
	pcase = "азоте"

/datum/reagent/oxygen
	name = "Кислород"
	description = "Газ без цвета и запаха."
	rugender = "male"
	ncase = "кислород"
	gcase = "кислорода"
	dcase = "кислороду"
	acase = "кислород"
	icase = "кислородом"
	pcase = "кислороде"

/datum/reagent/phosphorus
	name = "Фосфор"
	description = "Химический элемент, играющий важную роль в переносе энергии в организме."
	taste_description = "уксус"
	rugender = "male"
	ncase = "фосфор"
	gcase = "фосфора"
	dcase = "фосфору"
	acase = "фосфор"
	icase = "фосфором"
	pcase = "фосфоре"

/datum/reagent/potassium
	name = "Калий"
	description = "Мягкое твёрдое вещество с низкой температурой плавления. Бурно реагирует с водой."
	taste_description = "сладости"
	rugender = "male"
	ncase = "калий "
	gcase = "калия"
	dcase = "калию"
	acase = "калий "
	icase = "калием"
	pcase = "калии"

/datum/reagent/radium
	name = "Радий"
	description = "Радий является крайне радиоактивным щелочноземельным металлом."
	rugender = "male"
	ncase = "радий "
	gcase = "радия"
	dcase = "радию"
	acase = "радий "
	icase = "радием"
	pcase = "радии"

/datum/reagent/acid
	name = "Серная кислота"
	description = "Крайне едкая неорганическая кислота H2SO4."
	taste_description = "кислоты"
	rugender = "female"
	ncase = "серная кислота"
	gcase = "серной кислоты"
	dcase = "серной кислоте"
	acase = "серную кислоту"
	icase = "серной кислотой"
	pcase = "серной кислоте"

/datum/reagent/silicon
	name = "Кремний"
	description = "Четырёхвалентный металлоид; менее активен, чем углерод."
	rugender = "male"
	ncase = "кремний "
	gcase = "кремния"
	dcase = "кремнию"
	acase = "кремний "
	icase = "кремнием"
	pcase = "кремнии"

/datum/reagent/sodium
	name = "Натрий"
	description = "Химический элемент, вступает в реакцию с водой."
	taste_description = "солёного металла"
	rugender = "male"
	ncase = "натрий "
	gcase = "натрия"
	dcase = "натрию"
	acase = "натрий "
	icase = "натрием"
	pcase = "натрии"

/datum/reagent/sugar
	name = "Сахар"
	description = "Органическое соединение, известное как обыкновенный столовый сахар. Это белый кристаллический порошок без запаха с приятным сладким вкусом."
	taste_description = "сахара"
	rugender = "male"
	ncase = "сахар"
	gcase = "сахара"
	dcase = "сахару"
	acase = "сахар"
	icase = "сахаром"
	pcase = "сахаре"
	glass_name = "Сахар"
	glass_desc = "Органическое соединение, известное как обыкновенный столовый сахар. Это белый кристаллический порошок без запаха с приятным сладким вкусом."
	glass_rugender = "male"
	glass_ncase = "сахар"
	glass_gcase = "сахара"
	glass_dcase = "сахару"
	glass_acase = "сахар"
	glass_icase = "сахаром"
	glass_pcase = "сахаре"

/datum/reagent/sulfur
	name = "Сера"
	description = "Химический элемент с неприятным жгучим запахом."
	taste_description = "тухлых яиц"
	rugender = "male"
	ncase = "сер"
	gcase = "сера"
	dcase = "серу"
	acase = "сер"
	icase = "сером"
	pcase = "сере"

/datum/reagent/tungsten
	name = "Вольфрам"
	description = "Химический элемент, сильный окислитель."
	taste_description = "металла"
	rugender = "male"
	ncase = "вольфрам"
	gcase = "вольфрама"
	dcase = "вольфраму"
	acase = "вольфрам"
	icase = "вольфрамом"
	pcase = "вольфраме"

//Chemistry-Reagents-Food-Drinks.dm



//Chemistry-Reagents-Food-Drinks_vr.dm



//Chemistry-Reagents-Medicine.dm

/datum/reagent/inaprovaline
	name = "Инапровалин"
	description = "Инапровалин является синаптическим возбудителем и кардиостимулятором. Зачастую применяется для стабилизации состояния пациента."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "инапровалин"
	gcase = "инапровалина"
	dcase = "инапровалину"
	acase = "инапровалин"
	icase = "инапровалином"
	pcase = "инапровалине"

/datum/reagent/inaprovaline/topical
	name = "Инапровалаз"
	description = "Инапровалаз является разновидностью инапровалина, рассчитанной для наружного применения."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "инапровалаз"
	gcase = "инапровалаза"
	dcase = "инапровалазу"
	acase = "инапровалаз"
	icase = "инапровалазом"
	pcase = "инапровалазе"

/datum/reagent/bicaridine
	name = "Бикардин"
	description = "Бикардин является анальгетиком, применяемым для лечения травм и ушибов."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "бикардин"
	gcase = "бикардина"
	dcase = "бикардину"
	acase = "бикардин"
	icase = "бикардином"
	pcase = "бикардине"

/datum/reagent/bicaridine/topical
	name = "Бикардаз"
	description = "Бикардаз является разновидностью бикардина, рассчитанной для наружного применения."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "бикардаз"
	gcase = "бикардаза"
	dcase = "бикардазу"
	acase = "бикардаз"
	icase = "бикардазом"
	pcase = "бикардазе"

/datum/reagent/calciumcarbonate
	name = "Карбонат кальция"
	description = "Карбонат кальция является солью, зачастую используемой в качестве антацида."
	taste_description = "мела"
	rugender = "male"
	ncase = "карбонат кальция"
	gcase = "карбоната кальция"
	dcase = "карбонату кальция"
	acase = "карбонат кальция"
	icase = "карбонатом кальция"
	pcase = "карбонате кальция"

/datum/reagent/kelotane
	name = "Келотан"
	description = "Келотан является лекарством, применяемом при лечении ожогов."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "келотан"
	gcase = "келотана"
	dcase = "келотану"
	acase = "келотан"
	icase = "келотаном"
	pcase = "келотане"

/datum/reagent/dermaline
	name = "Дермалин"
	description = "Дермалин — следующий шаг в эволюции средств от ожогов. Работает в два раза быстрее келотана, и позволяет телу восстановить даже самые пострадавшие ткани."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "дермалин"
	gcase = "дермалина"
	dcase = "дермалину"
	acase = "дермалин"
	icase = "дермалином"
	pcase = "дермалине"

/datum/reagent/dermaline/topical
	name = "Дермалаз"
	description = "Дермалаз — версия дермалина, рассчитанная на внешнее применение."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "дермалаз"
	gcase = "дермалаза"
	dcase = "дермалазу"
	acase = "дермалаз"
	icase = "дермалазом"
	pcase = "дермалазе"

/datum/reagent/dylovene
	name = "Диловин"
	description = "Диловин является универсальным антитоксином."
	taste_description = "марли"
	rugender = "male"
	ncase = "диловин"
	gcase = "диловина"
	dcase = "диловину"
	acase = "диловин"
	icase = "диловином"
	pcase = "диловине"

/datum/reagent/carthatoline
	name = "Карфатолин"
	description = "Карфатолин назначается при отравлениях и способен быстро вывести из тела любые токсины."
	rugender = "male"
	ncase = "карфатолин"
	gcase = "карфатолина"
	dcase = "карфатолину"
	acase = "карфатолин"
	icase = "карфатолином"
	pcase = "карфатолине"

/datum/reagent/dexalin
	name = "Дексалин"
	description = "Дексалин применяется при кислородной недостаточности."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "дексалин"
	gcase = "дексалина"
	dcase = "дексалину"
	acase = "дексалин"
	icase = "дексалином"
	pcase = "дексалине"

/datum/reagent/dexalinp
	name = "Дексалин плюс"
	description = "Дексалин плюс применяется при кислородной недостаточности. Является крайне эффективным средством."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "дексалин плюс"
	gcase = "дексалина плюс"
	dcase = "дексалину плюс"
	acase = "дексалин плюс"
	icase = "дексалином плюс"
	pcase = "дексалине плюс"

/datum/reagent/tricordrazine
	name = "Трикордразин"
	description = "Трикордразин является сильным стимулятором. Он предназначен для лечения широкого спектра травм."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "трикордразин"
	gcase = "трикордразина"
	dcase = "трикордразину"
	acase = "трикордразин"
	icase = "трикордразином"
	pcase = "трикордразине"

/datum/reagent/tricorlidaze
	name = "Трикорлидаз"
	description = "Трикорлидаз является гелем наружного применения, изговленным из трикордразина и стерилизина."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "трикорлидаз"
	gcase = "трикорлидаза"
	dcase = "трикорлидазу"
	acase = "трикорлидаз"
	icase = "трикорлидазом"
	pcase = "трикорлидазе"

/datum/reagent/cryoxadone
	name = "Криоксадон"
	description = "Лекарственный препарат с едва ли не чудотворными свойствами. Подвох лишь в том, что температура организма для его работы должна быть не выше 170К."
	taste_description = "переспевших бананов"
	rugender = "male"
	ncase = "криоксадон"
	gcase = "криоксадона"
	dcase = "криоксадону"
	acase = "криоксадон"
	icase = "криоксадоном"
	pcase = "криоксадоне"

/datum/reagent/clonexadone
	name = "Клонексадон"
	description = "Жидкое соединение, схоже с теми, что используются в процессе клонирования. Может применяться совместно с криокапсулой для 'завершения' процесса клонирования."
	taste_description = "гнилых бананов"
	rugender = "male"
	ncase = "клонексадон"
	gcase = "клонексадона"
	dcase = "клонексадону"
	acase = "клонексадон"
	icase = "клонексадоном"
	pcase = "клонексадоне"

/datum/reagent/mortiferin
	name = "Мортиферин"
	description = "Жидкое соединение, схоже с теми, что используются в процессе клонирования. Используется в случаях токсического шока. Может нанести вред печени."
	taste_description = "мяса"
	rugender = "male"
	ncase = "мортиферин"
	gcase = "мортиферина"
	dcase = "мортиферину"
	acase = "мортиферин"
	icase = "мортиферином"
	pcase = "мортиферине"

/datum/reagent/necroxadone
	name = "Некроксадон"
	description = "Жидкое соединение, схоже с теми, что используются в процессе клонирования. Используется в случаях токсического шока."
	taste_description = "мяса"
	rugender = "male"
	ncase = "некроксадон"
	gcase = "некроксадона"
	dcase = "некроксадону"
	acase = "некроксадон"
	icase = "некроксадоном"
	pcase = "некроксадоне"

/datum/reagent/paracetamol
	name = "Парацетамол"
	description = "Известный большинству под названием тиленол, это лекарство является простым обезбаливающим."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "парацетамол"
	gcase = "парацетамола"
	dcase = "парацетамолу"
	acase = "парацетамол"
	icase = "парацетамолом"
	pcase = "парацетамоле"

/datum/reagent/tramadol
	name = "Трамадол"
	description = "Простое, однако эффективное обезбаливающее."
	taste_description = "кислинки"
	rugender = "male"
	ncase = "трамадол"
	gcase = "трамадола"
	dcase = "трамадолу"
	acase = "трамадол"
	icase = "трамадолом"
	pcase = "трамадоле"

/datum/reagent/oxycodone
	name = "Оксикодон"
	description = "Эффективное обезбаливающее, вызывающее привыкание."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "оксикодон"
	gcase = "оксикодона"
	dcase = "оксикодону"
	acase = "оксикодон"
	icase = "оксикодоном"
	pcase = "оксикодоне"

/datum/reagent/synaptizine
	name = "Синаптизин"
	description = "Синаптизин используется для лечения различных болезней."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "синаптизин"
	gcase = "синаптизина"
	dcase = "синаптизину"
	acase = "синаптизин"
	icase = "синаптизином"
	pcase = "синаптизине"

/datum/reagent/hyperzine
	name = "Гиперзин"
	description = "Гиперзин является длительным и крайне эффективным стимулятором мышц."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "гиперзин"
	gcase = "гиперзина"
	dcase = "гиперзину"
	acase = "гиперзин"
	icase = "гиперзином"
	pcase = "гиперзине"

/datum/reagent/alkysine
	name = "Алкизин"
	description = "Алкизин позволяет вылечить повреждения нервных тканей и клеток мозга после травмы."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "алкизин"
	gcase = "алкизина"
	dcase = "алкизину"
	acase = "алкизин"
	icase = "алкизином"
	pcase = "алкизине"

/datum/reagent/imidazoline
	name = "Имидазолин"
	description = "Позволяет лечить повреждения глаз."
	taste_description = "разбавленного токсина"
	rugender = "male"
	ncase = "имидазолин"
	gcase = "имидазолина"
	dcase = "имидазолину"
	acase = "имидазолин"
	icase = "имидазолином"
	pcase = "имидазолине"

/datum/reagent/peridaxon
	name = "Перидаксон"
	description = "Перидаксон способствует восстановлению внутренних органов и нервной системы. Использовать в малых дозах."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "перидаксон"
	gcase = "перидаксона"
	dcase = "перидаксону"
	acase = "перидаксон"
	icase = "перидаксоном"
	pcase = "перидаксоне"

/datum/reagent/osteodaxon
	name = "Остеодаксон"
	description = "Экспериментальный препарат, способствующий заживлению костей."
	rugender = "male"
	ncase = "остеодаксон"
	gcase = "остеодаксона"
	dcase = "остеодаксону"
	acase = "остеодаксон"
	icase = "остеодаксоном"
	pcase = "остеодаксоне"

/datum/reagent/myelamine
	name = "Миеламин"
	description = "Повышает эффективность тромбоцитов, тем самым способствуя свёртыванию внутренних кровотечений."
	rugender = "male"
	ncase = "миеламин"
	gcase = "миеламина"
	dcase = "миеламину"
	acase = "миеламин"
	icase = "миеламином"
	pcase = "миеламине"

/datum/reagent/respirodaxon
	name = "Респиродаксон"
	description = "Используется для восстановления тканей лёгких и других органов дыхания."
	taste_description = "металла"
	rugender = "male"
	ncase = "респиродаксон"
	gcase = "респиродаксона"
	dcase = "респиродаксону"
	acase = "респиродаксон"
	icase = "респиродаксоном"
	pcase = "респиродаксоне"

/datum/reagent/gastirodaxon
	name = "Гастиродаксон"
	description = "Применяется для восстановления тканей пищеварительной системы."
	taste_description = "мела"
	rugender = "male"
	ncase = "гастиродаксон"
	gcase = "гастиродаксона"
	dcase = "гастиродаксону"
	acase = "гастиродаксон"
	icase = "гастиродаксоном"
	pcase = "гастиродаксоне"

/datum/reagent/hepanephrodaxon
	name = "Гепанефродаксон"
	description = "Используется для восстановления тканей, участвующих в фильтрации."
	taste_description = "клея"
	rugender = "male"
	ncase = "гепанефродаксон"
	gcase = "гепанефродаксона"
	dcase = "гепанефродаксону"
	acase = "гепанефродаксон"
	icase = "гепанефродаксоном"
	pcase = "гепанефродаксоне"

/datum/reagent/cordradaxon
	name = "Кордрадаксон"
	description = "Используется для восстановления тканей в кровеносной системе."
	taste_description = "ржавчины"
	rugender = "male"
	ncase = "кордрадаксон"
	gcase = "кордрадаксона"
	dcase = "кордрадаксону"
	acase = "кордрадаксон"
	icase = "кордрадаксоном"
	pcase = "кордрадаксоне"

/datum/reagent/immunosuprizine
	name = "Иммуносупрезин"
	description = "Экспериментальный порошок, способный подавить отторжение органов."
	taste_description = "плоти"
	rugender = "male"
	ncase = "иммуносупрезин"
	gcase = "иммуносупрезина"
	dcase = "иммуносупрезину"
	acase = "иммуносупрезин"
	icase = "иммуносупрезином"
	pcase = "иммуносупрезине"

/datum/reagent/skrellimmuno
	name = "Малиш-квалем"
	description = "Странный маслянистый порошок, изобретённый Малиш-Катиш и применяемый для подавления отторжения органов."
	taste_description = "какой-то отравы"
	rugender = "male"
	ncase = "малиш-квалем"
	gcase = "малиш-квалема"
	dcase = "малиш-квалему"
	acase = "малиш-квалем"
	icase = "малиш-квалемом"
	pcase = "малиш-квалеме"

/datum/reagent/ryetalyn
	name = "Риеталин"
	description = "Риеталин применяется для борьбы с генетическими дефектами и повреждениями."
	taste_description = "кислоты"
	rugender = "male"
	ncase = "риеталин"
	gcase = "риеталина"
	dcase = "риеталину"
	acase = "риеталин"
	icase = "риеталином"
	pcase = "риеталине"

/datum/reagent/ethylredoxrazine
	name = "Этилредоксразин"
	description = "Сильный окислитель, вступающий в реакцию с этанолом."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "этилредоксразин"
	gcase = "этилредоксразина"
	dcase = "этилредоксразину"
	acase = "этилредоксразин"
	icase = "этилредоксразином"
	pcase = "этилредоксразине"

/datum/reagent/hyronalin
	name = "Гироналин"
	description = "Гироналин является лекарственным препаратом, применяемым для борьбы с воздействием радиации."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "гироналин"
	gcase = "гироналина"
	dcase = "гироналину"
	acase = "гироналин"
	icase = "гироналином"
	pcase = "гироналине"

/datum/reagent/arithrazine
	name = "Аритразин"
	description = "Аритразин является нестабильным препаратом, применяемым для борьбы с серьёзными последствиями воздействия радиации."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "аритразин"
	gcase = "аритразина"
	dcase = "аритразину"
	acase = "аритразин"
	icase = "аритразином"
	pcase = "аритразине"

/datum/reagent/spaceacillin
	name = "Космоциллин"
	description = "Универсальный антивирусный препарат."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "космоциллин"
	gcase = "космоциллина"
	dcase = "космоциллину"
	acase = "космоциллин"
	icase = "космоциллином"
	pcase = "космоциллине"

/datum/reagent/corophizine
	name = "Корофизин"
	description = "Антибиотик широкого применения. Эффективный, однако неприятный."
	taste_description = "горелого хлеба"
	rugender = "male"
	ncase = "корофизин"
	gcase = "корофизина"
	dcase = "корофизину"
	acase = "корофизин"
	icase = "корофизином"
	pcase = "корофизине"

/datum/reagent/spacomycaze
	name = "Космомиказ"
	description = "Обезбаливающий гель-антибиотик."
	taste_description = "масла"
	rugender = "male"
	ncase = "космомиказ"
	gcase = "космомиказа"
	dcase = "космомиказу"
	acase = "космомиказ"
	icase = "космомиказом"
	pcase = "космомиказе"

/datum/reagent/sterilizine
	name = "Стерилизин"
	description = "Дезинфицирует раны перед операцией, а также растворяет кровь."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "стерилизин"
	gcase = "стерилизина"
	dcase = "стерилизину"
	acase = "стерилизин"
	icase = "стерилизином"
	pcase = "стерилизине"

/datum/reagent/leporazine
	name = "Лепоразин"
	description = "Лепоразин позволяет стабилизировать температуру организма."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "лепоразин"
	gcase = "лепоразина"
	dcase = "лепоразину"
	acase = "лепоразин"
	icase = "лепоразином"
	pcase = "лепоразине"

/datum/reagent/rezadone
	name = "Резадон"
	description = "Порошок с едва ли не волшебными свойствами. Он позволяет бороться с генетическими повреждениями в гуманоидных организмах, однако чрезмерное употребление может привести к побочным эффектам."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "резадон"
	gcase = "резадона"
	dcase = "резадону"
	acase = "резадон"
	icase = "резадоном"
	pcase = "резадоне"

/datum/reagent/methylphenidate
	name = "Метилфенидат"
	description = "Способствует концентрации разума."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "метилфенидат"
	gcase = "метилфенидата"
	dcase = "метилфенидату"
	acase = "метилфенидат"
	icase = "метилфенидатом"
	pcase = "метилфенидате"

/datum/reagent/citalopram
	name = "Циталопрам"
	description = "Антидепрессант, помогает стабилизировать разум."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "циталопрам"
	gcase = "циталопрама"
	dcase = "циталопраму"
	acase = "циталопрам"
	icase = "циталопрамом"
	pcase = "циталопраме"

/datum/reagent/paroxetine
	name = "Пароксетин"
	description = "Антидепрессант, стабилизирует разум, однако обладает побочными эффектами."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "пароксетин"
	gcase = "пароксетина"
	dcase = "пароксетину"
	acase = "пароксетин"
	icase = "пароксетином"
	pcase = "пароксетине"

/datum/reagent/qerr_quem
	name = "Керр-кем"
	description = "Эффективный стимулятор, используемый в качестве антидепрессанта от волнения, открытый кастой Керр-Катиш."
	taste_description = "мяты"
	rugender = "male"
	ncase = "керр-кем"
	gcase = "керр-кема"
	dcase = "керр-кему"
	acase = "керр-кем"
	icase = "керр-кемом"
	pcase = "керр-кеме"

/datum/reagent/healing_nanites
	name = "Восстанавливающие наниты"
	description = "Миниатюрные медицинские наноботы, быстро и эффективно восстанавливающие повреждения в организме."
	taste_description = "металла"
	rugender = "plural"
	ncase = "восстанавливающие наниты"
	gcase = "восстанавливающих нанитов"
	dcase = "восстанавливающим нанитам"
	acase = "восстанавливающие наниты"
	icase = "восстанавливающими нанитами"
	pcase = "восстанавливающих нанитах"

/datum/reagent/menthol
	name = "Ментол"
	description = "Обладает мятным вкусном и слабым обезбаливающим эффектом."
	taste_description = "мяты"
	rugender = "male"
	ncase = "ментол"
	gcase = "ментола"
	dcase = "ментолу"
	acase = "ментол"
	icase = "ментолом"
	pcase = "ментоле"

//Chemistry-Reagents-Medicine_vr.dm

/datum/reagent/adranol
	name = "Адранол"
	description = "Слабительное, успокаивающее нервы пациента."
	taste_description = "молока"
	rugender = "male"
	ncase = "адранол"
	gcase = "адранола"
	dcase = "адранолу"
	acase = "адранол"
	icase = "адранолом"
	pcase = "адраноле"

/datum/reagent/numbing_enzyme
	name = "Обезбаливающий фермент"
	description = "Органическое обезбаливающее."
	taste_description = "кислинки"
	rugender = "male"
	ncase = "обезбаливающий фермент"
	gcase = "обезбаливающего фермента"
	dcase = "обезбаливающему ферменту"
	acase = "обезбаливающий фермент"
	icase = "обезбаливающим ферментом"
	pcase = "обезбаливающем ферменте"

/datum/reagent/vermicetol
	name = "Вермицетол"
	description = "Эффективный препарат, позволяющий быстро восстановить физические повреждения."
	taste_description = "искр"
	rugender = "male"
	ncase = "вермицетол"
	gcase = "вермицетола"
	dcase = "вермицетолу"
	acase = "вермицетол"
	icase = "вермицетолом"
	pcase = "вермицетоле"

/datum/reagent/sleevingcure
	name = "Лекарство Китсухана"
	description = "Крайне редкое лекарство, представляемое KHI и позволяющее предотвратить побочные эффекты ресливинга при использовании несовершенной техники."
	taste_description = "шоколадного масла"
	rugender = "neuter"
	ncase = "Лекарство Китсухана"
	gcase = "Лекарства Китсухана"
	dcase = "Лекарству Китсухана"
	acase = "Лекарство Китсухана"
	icase = "Лекарством Китсухана"
	pcase = "Лекарстве Китсухана"

//Chemistry-Reagents-Modifiers.dm

/datum/reagent/modapplying
	name = "Сок агрессии"
	description = "Жидкость, способная вызывать продолжительное состояние агрессии и прилив сил."
	taste_description = "металла"
	rugender = "male"
	ncase = "сок агрессии"
	gcase = "сока агрессии"
	dcase = "соку агрессии"
	acase = "сок агрессии"
	icase = "соком агрессии"
	pcase = "соке агрессии"

/datum/reagent/modapplying/cryofluid
	name = "Криогенная суспензия"
	description = "Странная жидкость, быстро поглощающая тепловую энергию из тел, с которыми контактирует."
	taste_description = "сибирского ада"
	rugender = "female"
	ncase = "криогенная суспензия"
	gcase = "криогенной суспензии"
	dcase = "криогенной суспензии"
	acase = "криогенную суспензию"
	icase = "криогенной суспензией"
	pcase = "криогенной суспензии"

/datum/reagent/modapplying/vatstabilizer
	name = "Ингибитор роста клонов"
	description = "Соединение, производимое NanoTrasen с использованием секретной формулы из форона и токсинов для предотвращения излишнего роста клонов за предусмотренные рамки."
	taste_description = "кислого клея"
	rugender = "male"
	ncase = "ингибитор роста клонов"
	gcase = "ингибитора роста клонов"
	dcase = "ингибитору роста клонов"
	acase = "ингибитор роста клонов"
	icase = "ингибитором роста клонов"
	pcase = "ингибиторе роста клонов"

//Chemistry-Reagents-Other.dm

/datum/reagent/crayon_dust
	name = "Восковой порошок"
	description = "Окрашенный порошок, полученный в результате измельчения цветных восковых мелков."
	taste_description = "измельчённого воска"
	rugender = "male"
	ncase = "восковой порошок"
	gcase = "воскового порошка"
	dcase = "восковому порошку"
	acase = "восковой порошок"
	icase = "восковым порошком"
	pcase = "восковом порошке"

/datum/reagent/crayon_dust/red
	name = "Красный восковой порошок"
	rugender = "male"
	ncase = "красный восковой порошок"
	gcase = "красного воскового порошка"
	dcase = "красному восковому порошку"
	acase = "красный восковой порошок"
	icase = "красным восковым порошком"
	pcase = "красном восковом порошке"

/datum/reagent/crayon_dust/orange
	name = "Оранжевый восковой порошок"
	rugender = "male"
	ncase = "оранжевый восковой порошок"
	gcase = "оранжевого воскового порошка"
	dcase = "оранжевому восковому порошку"
	acase = "оранжевый восковой порошок"
	icase = "оранжевым восковым порошком"
	pcase = "оранжевом восковом порошке"

/datum/reagent/crayon_dust/yellow
	name = "Жёлтый восковой порошок"
	rugender = "male"
	ncase = "жёлтый восковой порошок"
	gcase = "жёлтого воскового порошка"
	dcase = "жёлтому восковому порошку"
	acase = "жёлтый восковой порошок"
	icase = "жёлтым восковым порошком"
	pcase = "жёлтом восковом порошке"

/datum/reagent/crayon_dust/green
	name = "Зелёный восковой порошок"
	rugender = "male"
	ncase = "зелёный восковой порошок"
	gcase = "зелёного воскового порошка"
	dcase = "зелёному восковому порошку"
	acase = "зелёный восковой порошок"
	icase = "зелёным восковым порошком"
	pcase = "зелёном восковом порошке"

/datum/reagent/crayon_dust/blue
	name = "Синий восковой порошок"
	rugender = "male"
	ncase = "синий восковой порошок"
	gcase = "синего воскового порошка"
	dcase = "синему восковому порошку"
	acase = "синий восковой порошок"
	icase = "синим восковым порошком"
	pcase = "синем восковом порошке"

/datum/reagent/crayon_dust/purple
	name = "Фиолетовый восковой порошок"
	rugender = "male"
	ncase = "фиолетовый восковой порошок"
	gcase = "фиолетового воскового порошка"
	dcase = "фиолетовому восковому порошку"
	acase = "фиолетовый восковой порошок"
	icase = "фиолетовым восковым порошком"
	pcase = "фиолетовом восковом порошке"

/datum/reagent/crayon_dust/grey
	name = "Серый восковой порошок"
	rugender = "male"
	ncase = "серый восковой порошок"
	gcase = "серого воскового порошка"
	dcase = "серому восковому порошку"
	acase = "серый восковой порошок"
	icase = "серым восковым порошком"
	pcase = "сером восковом порошке"

/datum/reagent/crayon_dust/brown
	name = "Коричневый восковой порошок"
	rugender = "male"
	ncase = "коричневый восковой порошок"
	gcase = "коричневого воскового порошка"
	dcase = "коричневому восковому порошку"
	acase = "коричневый восковой порошок"
	icase = "коричневым восковым порошком"
	pcase = "коричневом восковом порошке"

/datum/reagent/marker_ink
	name = "Маркерные чернила"
	description = "Окрашенные чернила, используемые в маркерах."
	taste_description = "сильной горечи"
	rugender = "plural"
	ncase = "маркерные чернила"
	gcase = "маркерных чернил"
	dcase = "маркерным чернилам"
	acase = "маркерные чернила"
	icase = "маркерными чернилами"
	pcase = "маркерных чернилах"

/datum/reagent/marker_ink/black
	name = "Чёрные маркерные чернила"
	rugender = "plural"
	ncase = "чёрные маркерные чернила"
	gcase = "чёрных маркерных чернил"
	dcase = "чёрным маркерным чернилам"
	acase = "чёрные маркерные чернила"
	icase = "чёрными маркерными чернилами"
	pcase = "чёрных маркерных чернилах"

/datum/reagent/marker_ink/red
	name = "Красные маркерные чернила"
	rugender = "plural"
	ncase = "красные маркерные чернила"
	gcase = "красных маркерных чернил"
	dcase = "красным маркерным чернилам"
	acase = "красные маркерные чернила"
	icase = "красными маркерными чернилами"
	pcase = "красных маркерных чернилах"

/datum/reagent/marker_ink/orange
	name = "Оранжевые маркерные чернила"
	rugender = "plural"
	ncase = "оранжевые маркерные чернила"
	gcase = "оранжевых маркерных чернил"
	dcase = "оранжевым маркерным чернилам"
	acase = "оранжевые маркерные чернила"
	icase = "оранжевыми маркерными чернилами"
	pcase = "оранжевых маркерных чернилах"

/datum/reagent/marker_ink/yellow
	name = "Жёлтые маркерные чернила"
	rugender = "plural"
	ncase = "жёлтые маркерные чернила"
	gcase = "жёлтых маркерных чернил"
	dcase = "жёлтым маркерным чернилам"
	acase = "жёлтые маркерные чернила"
	icase = "жёлтыми маркерными чернилами"
	pcase = "жёлтых маркерных чернилах"

/datum/reagent/marker_ink/green
	name = "Зелёные маркерные чернила"
	rugender = "plural"
	ncase = "зелёные маркерные чернила"
	gcase = "зелёных маркерных чернил"
	dcase = "зелёным маркерным чернилам"
	acase = "зелёные маркерные чернила"
	icase = "зелёными маркерными чернилами"
	pcase = "зелёных маркерных чернилах"

/datum/reagent/marker_ink/blue
	name = "Синие маркерные чернила"
	rugender = "plural"
	ncase = "синие маркерные чернила"
	gcase = "синих маркерных чернил"
	dcase = "синим маркерным чернилам"
	acase = "синие маркерные чернила"
	icase = "синими маркерными чернилами"
	pcase = "синих маркерных чернилах"

/datum/reagent/marker_ink/purple
	name = "Фиолетовые маркерные чернила"
	rugender = "plural"
	ncase = "фиолетовые маркерные чернила"
	gcase = "фиолетовых маркерных чернил"
	dcase = "фиолетовым маркерным чернилам"
	acase = "фиолетовые маркерные чернила"
	icase = "фиолетовыми маркерными чернилами"
	pcase = "фиолетовых маркерных чернилах"

/datum/reagent/marker_ink/grey
	name = "Серые маркерные чернила"
	rugender = "plural"
	ncase = "серые маркерные чернила"
	gcase = "серых маркерных чернил"
	dcase = "серым маркерным чернилам"
	acase = "серые маркерные чернила"
	icase = "серыми маркерными чернилами"
	pcase = "серых маркерных чернилах"

/datum/reagent/marker_ink/brown
	name = "Коричневые маркерные чернила"
	rugender = "plural"
	ncase = "коричневые маркерные чернила"
	gcase = "коричневых маркерных чернил"
	dcase = "коричневым маркерным чернилам"
	acase = "коричневые маркерные чернила"
	icase = "коричневыми маркерными чернилами"
	pcase = "коричневых маркерных чернилах"

/datum/reagent/paint
	name = "Краска"
	description = "Такая краска будет держаться практически на любом объекте."
	taste_description = "мела"
	rugender = "female"
	ncase = "краска"
	gcase = "краски"
	dcase = "краске"
	acase = "краску"
	icase = "краской"
	pcase = "краске"

/datum/reagent/adminordrazine
	name = "Админордразин"
	description = "Это магия. Мы ничего не обязаны объяснять."
	taste_description = "бвоинка"
	rugender = "male"
	ncase = "админордразин"
	gcase = "админордразина"
	dcase = "админордразину"
	acase = "админордразин"
	icase = "админордразином"
	pcase = "админордразине"
	glass_name = "Жидкое золото"
	glass_desc = "Это магия. Мы ничего не обязаны объяснять."
	glass_rugender = "neuter"
	glass_ncase = "жидкое золото"
	glass_gcase = "жидкого золота"
	glass_dcase = "жидкому золоту"
	glass_acase = "жидкое золото"
	glass_icase = "жидкым золотом"
	glass_pcase = "жидком золоте"

/datum/reagent/gold
	name = "Золото"
	description = "Золото — это блестящий металл, самый пластичный и ковкий из известных."
	taste_description = "металла"
	rugender = "neuter"
	ncase = "золото"
	gcase = "золота"
	dcase = "золоту"
	acase = "золото"
	icase = "золотом"
	pcase = "золоте"

/datum/reagent/silver
	name = "Серебро"
	description = "Мягкий переходный металл белого цвета. Обладает самой высокой электро- и теплопроводностью."
	taste_description = "металла"
	rugender = "neuter"
	ncase = "серебро"
	gcase = "серебра"
	dcase = "серебру"
	acase = "серебро"
	icase = "серебром"
	pcase = "серебре"

/datum/reagent/uranium
	name ="Уран"
	description = "Радиоактивный химический элемент из семейства актиноидов."
	taste_description = "металла"
	rugender = "male"
	ncase = "уран"
	gcase = "урана"
	dcase = "урану"
	acase = "уран"
	icase = "ураном"
	pcase = "уране"

/datum/reagent/platinum
	name = "Платина"
	description = "Ковкий, пластичный металл с низкой активностью. Коррозионностойкий."
	taste_description = "металла"
	rugender = "female"
	ncase = "платина"
	gcase = "платини"
	dcase = "платине"
	acase = "платину"
	icase = "платиной"
	pcase = "платине"

/datum/reagent/adrenaline
	name = "Адреналин"
	description = "Адреналин является гормоном, а также используется при сердечных приступах и других случаях аритмии."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "адреналин"
	gcase = "адреналина"
	dcase = "адреналину"
	acase = "адреналин"
	icase = "адреналином"
	pcase = "адреналине"

/datum/reagent/water/holywater
	name = "Святая вода"
	description = "Эта жидкость своеобразно влияет на мозг."
	taste_description = "воды"
	rugender = "female"
	ncase = "святая вода"
	gcase = "святой воды"
	dcase = "святой воде"
	acase = "святую воду"
	icase = "святой водой"
	pcase = "святой воде"
	glass_name = "Святая вода"
	glass_desc = "Эта жидкость своеобразно влияет на мозг."
	glass_rugender = "female"
	glass_ncase = "святая вода"
	glass_gcase = "святой воды"
	glass_dcase = "святой воде"
	glass_acase = "святую воду"
	glass_icase = "святой водой"
	glass_pcase = "святой воде"

/datum/reagent/ammonia
	name = "Аммиак"
	description = "Едкая субстанция, применяемая в удобрениях и чистящих средствах."
	taste_description = "отравы"
	rugender = "male"
	ncase = "аммиак"
	gcase = "аммиака"
	dcase = "аммиаку"
	acase = "аммиак"
	icase = "аммиаком"
	pcase = "аммиаке"

/datum/reagent/diethylamine
	name = "Диэтиламин"
	description = "Вторичный амин, довольно едкий."
	taste_description = "железа"
	rugender = "male"
	ncase = "диэтиламин"
	gcase = "диэтиламина"
	dcase = "диэтиламину"
	acase = "диэтиламин"
	icase = "диэтиламином"
	pcase = "диэтиламине"

/datum/reagent/fluorosurfactantr
	name = "Поверхностно-активная пена"
	description = "Фторосодержащая сульфокислота, образующая пену в реакции с водой."
	taste_description = "металла"
	rugender = "female"
	ncase = "поверхностно-активная пена"
	gcase = "поверхностно-активной пены"
	dcase = "поверхностно-активной пене"
	acase = "поверхностно-активную пену"
	icase = "поверхностно-активной пеной"
	pcase = "поверхностно-активной пене"

/datum/reagent/foaming_agent
	name = "Пенообразователь"
	description = "Вещество, образущее пену в реакции с сильной кислотой и лёгким металлом."
	taste_description = "металла"
	rugender = "male"
	ncase = "пенообразователь"
	gcase = "пенообразователя"
	dcase = "пенообразователю"
	acase = "пенообразователь"
	icase = "пенообразователем"
	pcase = "пенообразователе"

/datum/reagent/thermite
	name = "Термит"
	description = "Термит вызывает алюминотермическую реакцию, известную как термитная. С помощью него можно плавить стены."
	taste_description = "сладкого металла"
	rugender = "male"
	ncase = "термит"
	gcase = "термита"
	dcase = "термиту"
	acase = "термит"
	icase = "термитом"
	pcase = "термите"

/datum/reagent/space_cleaner
	name = "Космический очиститель"
	description = "Соединение, используемое в качестве чистящего средства. Теперь на 50% больше гипохлорита натрия!"
	taste_description = "кислинки"
	rugender = "male"
	ncase = "космический очиститель"
	gcase = "космического очистителя"
	dcase = "космическому очистителю"
	acase = "космический очиститель"
	icase = "космическим очистителем"
	pcase = "космическом очистителе"

/datum/reagent/lube
	name = "Космическая смазка"
	description = "Смазка позволяет уменьшить трение между двумя движущимися поверхностями."
	taste_description = "слизи"
	rugender = "female"
	ncase = "космическая смазка"
	gcase = "космической смазки"
	dcase = "космической смазке"
	acase = "космическую смазку"
	icase = "космической смазкой"
	pcase = "космической смазке"

/datum/reagent/silicate
	name = "Силикат"
	description = "Соединение, применяемое для упрочнения стекла."
	taste_description = "пластика"
	rugender = "male"
	ncase = "силикат"
	gcase = "силиката"
	dcase = "силикату"
	acase = "силикат"
	icase = "силикатом"
	pcase = "силикате"

/datum/reagent/glycerol
	name = "Глицерин"
	description = "Глицерин — простой одноатомный спирт."
	taste_description = "сладости"
	rugender = "male"
	ncase = "глицерин"
	gcase = "глицерина"
	dcase = "глицерину"
	acase = "глицерин"
	icase = "глицерином"
	pcase = "глицерине"

/datum/reagent/nitroglycerin
	name = "Нитроглицерин"
	description = "Бесцветная маслянистая жидкость, получаемая в результате азотирования глицерина. Nitroglycerin is a heavy, colorless, oily, explosive liquid obtained by nitrating glycerol."
	taste_description = "масла"
	rugender = "male"
	ncase = "нитроглицерин"
	gcase = "нитроглицерина"
	dcase = "нитроглицерину"
	acase = "нитроглицерин"
	icase = "нитроглицерином"
	pcase = "нитроглицерине"

/datum/reagent/coolant
	name = "Хладагент"
	description = "Промышленный охладитель."
	taste_description = "кислоты"
	rugender = "male"
	ncase = "хладагент"
	gcase = "хладагента"
	dcase = "хладагенту"
	acase = "хладагент"
	icase = "хладагентом"
	pcase = "хладагенте"

/datum/reagent/ultraglue
	name = "Ультра клей"
	description = "Очень сильный клей."
	taste_description = "уроков трудов"
	rugender = "male"
	ncase = "ультра клей"
	gcase = "ультра клея"
	dcase = "ультра клею"
	acase = "ультра клей"
	icase = "ультра клеем"
	pcase = "ультра клее"

/datum/reagent/woodpulp
	name = "Деревянная стружка"
	description = "Масса из деревянных волокон."
	taste_description = "дерева"
	rugender = "female"
	ncase = "деревянная стружка"
	gcase = "деревянной стружки"
	dcase = "деревянной стружке"
	acase = "деревянную стружку"
	icase = "деревянной стружкой"
	pcase = "деревянной стружке"

/datum/reagent/luminol
	name = "Люминол"
	description = "Соединение, вступающее в реакцию с кровью."
	taste_description = "металла"
	rugender = "male"
	ncase = "люминол"
	gcase = "люминола"
	dcase = "люминолу"
	acase = "люминол"
	icase = "люминолом"
	pcase = "люминоле"

/datum/reagent/nutriment/biomass
	name = "Биомасса"
	description = "Субстанция, состоящая из соединений, необходимых для появления жизни."
	taste_description = "солёного мяса"
	rugender = "female"
	ncase = "биомасса"
	gcase = "биомассы"
	dcase = "биомассе"
	acase = "биомассу"
	icase = "биомассой"
	pcase = "биомассе"

/datum/reagent/mineralfluid
	name = "Обогащённая минералами жидкость"
	description = "Тёплая жидкость, обогащённая минералами."
	taste_description = "соли"
	rugender = "female"
	ncase = "обогащённая минералами жидкость"
	gcase = "обогащённой минералами жидкости"
	dcase = "обогащённой минералами жидкости"
	acase = "обогащённую минералами жидкость"
	icase = "обогащённой минералами жидкостью"
	pcase = "обогащённой минералами жидкости"

/datum/reagent/defective_nanites
	name = "Бракованные наниты"
	description = "Миниатюрные медицинские роботы. Они дефективны и вредят организму, но, к счастью, не способны размножаться."
	taste_description = "металла"
	rugender = "plural"
	ncase = "бракованные наниты"
	gcase = "бракованных нанитов"
	dcase = "бракованным нанитам"
	acase = "бракованные наниты"
	icase = "бракованными нанитами"
	pcase = "бракованных нанитах"

/datum/reagent/fishbait
	name = "Наживка"
	description = "Масса органического происхождения, на которую клюют рыбы."
	taste_description = "земли"
	rugender = "female"
	ncase = "наживка"
	gcase = "наживки"
	dcase = "наживке"
	acase = "наживку"
	icase = "наживкой"
	pcase = "наживке"

//Chemistry-Reagents-Toxins.dm

/datum/reagent/toxin
	name = "Токсин"
	description = "Токсичное химическое вещество."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "токсин"
	gcase = "токсина"
	dcase = "токсину"
	acase = "токсин"
	icase = "токсином"
	pcase = "токсине"

/datum/reagent/toxin/plasticide
	name = "Пластицид"
	description = "Жидкий пластик. Не рекомендуется употреблять."
	taste_description = "пластмассы"
	rugender = "male"
	ncase = "пластицид"
	gcase = "пластицида"
	dcase = "пластициду"
	acase = "пластицид"
	icase = "пластицидом"
	pcase = "пластициде"

/datum/reagent/toxin/amatoxin
	name = "Аматоксин"
	description = "Мощный яд, создаваемый определённым видом грибов."
	taste_description = "грибов"
	rugender = "male"
	ncase = "аматоксин"
	gcase = "аматоксина"
	dcase = "аматоксину"
	acase = "аматоксин"
	icase = "аматоксином"
	pcase = "аматоксине"

/datum/reagent/toxin/carpotoxin
	name = "Карпотоксин"
	description = "Смертельный нейротоксин, выделяемый космическими карпами."
	taste_description = "рыбы"
	rugender = "male"
	ncase = "карпотоксин"
	gcase = "карпотоксина"
	dcase = "карпотоксину"
	acase = "карпотоксин"
	icase = "карпотоксином"
	pcase = "карпотоксине"

/datum/reagent/toxin/neurotoxic_protein
	name = "Ядовитый протеин"
	description = "Слабый нейротоксин, встречающийся в сифской рыбе."
	taste_description = "рыбы"
	rugender = "male"
	ncase = "ядовитый протеин"
	gcase = "ядовитого протеина"
	dcase = "ядовитому протеину"
	acase = "ядовитый протеин"
	icase = "ядовитым протеином"
	pcase = "ядовитом протеине"

/datum/reagent/toxin/hydrophoron
	name = "Гидрофорон"
	description = "Легковоспламеняемые молекулы, созданные в процессе синтеза дейтерия."
	rugender = "male"
	ncase = "гидрофорон"
	gcase = "гидрофорона"
	dcase = "гидрофорону"
	acase = "гидрофорон"
	icase = "гидрофороном"
	pcase = "гидрофороне"

/datum/reagent/toxin/lead
	name = "Свинец"
	description = "Химический элемент."
	rugender = "male"
	ncase = "свинец"
	gcase = "свинца"
	dcase = "свинцу"
	acase = "свинец"
	icase = "свинцом"
	pcase = "свинце"

/datum/reagent/toxin/spidertoxin
	name = "Паучий токсин"
	description = "Растворяющий токсин, выделяемый гигантскими пауками."
	rugender = "male"
	ncase = "паучий токсин"
	gcase = "паучьего токсина"
	dcase = "паучьему токсину"
	acase = "паучий токсин"
	icase = "паучьим токсином"
	pcase = "паучьем токсине"

/datum/reagent/toxin/phoron
	name = "Форон"
	description = "Форон в жидкой форме."
	rugender = "male"
	ncase = "форон"
	gcase = "форона"
	dcase = "форону"
	acase = "форон"
	icase = "фороном"
	pcase = "фороне"

/datum/reagent/toxin/cyanide
	name = "Цианид"
	description = "Ядовитое химическое соединение."
	taste_description = "миндаля"
	rugender = "male"
	ncase = "цианид"
	gcase = "цианида"
	dcase = "цианиду"
	acase = "цианид"
	icase = "цианидом"
	pcase = "цианиде"

/datum/reagent/toxin/mold
	name = "Плесень"
	description = "Плесень вызывает биологическое разложение в органических веществах. Эта плесень содержит микотоксины и опасна для людей."
	taste_description = "плесени"
	rugender = "female"
	ncase = "плесень"
	gcase = "плесени"
	dcase = "плесени"
	acase = "плесень"
	icase = "плесенью"
	pcase = "плесени"

/datum/reagent/toxin/expired_medicine
	name = "Просроченное лекарство"
	description = "Некое жидкое лекарство, уже давно просроченное. Сейчас от него больше вреда, чем пользы."
	taste_description = "чего-то горького"
	rugender = "neuter"
	ncase = "просроченное лекарство"
	gcase = "просроченного лекарства"
	dcase = "просроченному лекарству"
	acase = "просроченное лекарство"
	icase = "просроченным лекарством"
	pcase = "просроченном лекарстве"

/datum/reagent/toxin/stimm
	name = "Стимм"
	description = "Самодельный стимулятор, обладающий серьёзными побочными эффектами."
	taste_description = "чего-то сладкого"
	rugender = "male"
	ncase = "стимм"
	gcase = "стимма"
	dcase = "стимму"
	acase = "стимм"
	icase = "стиммом"
	pcase = "стимме"

/datum/reagent/toxin/potassium_chloride
	name = "Хлорид калия"
	description = "Вкусная соль, останавливающая сердце при в введении в сердечные мышцы."
	taste_description = "соли"
	rugender = "male"
	ncase = "хлорид калия"
	gcase = "хлорида калия"
	dcase = "хлориду калия"
	acase = "хлорид калия"
	icase = "хлоридом калия"
	pcase = "хлориде калия"

/datum/reagent/toxin/potassium_chlorophoride
	name = "Хлорофорид калия"
	description = "Химическое вещество на основе хлорида калия, останавливающее сердце в хирургических целях."
	taste_description = "соли"
	rugender = "male"
	ncase = "хлорофорид калия"
	gcase = "хлорофорида калия"
	dcase = "хлорофориду калия"
	acase = "хлорофорид калия"
	icase = "хлорофоридом калия"
	pcase = "хлорофориде калия"

/datum/reagent/toxin/zombiepowder
	name = "Зомби-порошок"
	description = "Сильный нейротоксин, вызывающий состояние, сравнимое со смертью."
	taste_description = "паралича"
	rugender = "male"
	ncase = "зомби-порошок"
	gcase = "зомби-порошка"
	dcase = "зомби-порошку"
	acase = "зомби-порошок"
	icase = "зомби-порошком"
	pcase = "зомби-порошке"

/datum/reagent/toxin/lichpowder
	name = "Лич-порошок"
	description = "Стабилизированное соединение, вызывающее странное состояние нежитья."
	rugender = "male"
	ncase = "лич-порошок"
	gcase = "лич-порошка"
	dcase = "лич-порошку"
	acase = "лич-порошок"
	icase = "лич-порошком"
	pcase = "лич-порошке"

/datum/reagent/toxin/fertilizer
	name = "Удобрение"
	description = "Химическая смесь, способствующая росту растений."
	taste_description = "минеральных веществ"
	rugender = "neuter"
	ncase = "удобрение"
	gcase = "удобрения"
	dcase = "удобрению"
	acase = "удобрение"
	icase = "удобрением"
	pcase = "удобрении"

/datum/reagent/toxin/fertilizer/eznutrient
	name = "Удобрение \"Добротное\""
	rugender = "neuter"
	ncase = "удобрение \"Добротное\""
	gcase = "удобрения \"Добротное\""
	dcase = "удобрению \"Добротное\""
	acase = "удобрение \"Добротное\""
	icase = "удобрением \"Добротное\""
	pcase = "удобрении \"Добротное\""

/datum/reagent/toxin/fertilizer/left4zed
	name = "Удобрение \"Расцвет сил\""
	rugender = "neuter"
	ncase = "удобрение \"Расцвет сил\""
	gcase = "удобрения \"Расцвет сил\""
	dcase = "удобрению \"Расцвет сил\""
	acase = "удобрение \"Расцвет сил\""
	icase = "удобрением \"Расцвет сил\""
	pcase = "удобрении \"Расцвет сил\""

/datum/reagent/toxin/fertilizer/robustharvest
	name = "Удобрение \"Урожайный сезон\""
	rugender = "neuter"
	ncase = "удобрение \"Урожайный сезон\""
	gcase = "удобрения \"Урожайный сезон\""
	dcase = "удобрению \"Урожайный сезон\""
	acase = "удобрение \"Урожайный сезон\""
	icase = "удобрением \"Урожайный сезон\""
	pcase = "удобрении \"Урожайный сезон\""

/datum/reagent/toxin/fertilizer/tannin
	name = "Таннин"
	description = "Химическое соединение, выделяемое некоторыми растениями в качестве органического пестицида. Позволяет также контролировать рост."
	taste_description = "морщин"
	rugender = "male"
	ncase = "таннин"
	gcase = "таннина"
	dcase = "таннину"
	acase = "таннин"
	icase = "таннином"
	pcase = "таннине"

/datum/reagent/toxin/plantbgone
	name = "\"ДолойТраву\""
	description = "Вредоносная токсичная смесь, предназначенная для ликвидации растительности. Не употреблять!"
	rugender = "male"
	ncase = "\"ДолойТраву\""
	gcase = "\"ДолойТраву\""
	dcase = "\"ДолойТраву\""
	acase = "\"ДолойТраву\""
	icase = "\"ДолойТраву\""
	pcase = "\"ДолойТраву\""

/datum/reagent/toxin/sifslurry
	name = "Сифская смола"
	description = "Смола органического происхождения, состоящая из сифских флюоресцентных бактерий."
	taste_description = "кислинки"
	rugender = "female"
	ncase = "сифская смола"
	gcase = "сифской смолы"
	dcase = "сифской смоле"
	acase = "сифскую смолу"
	icase = "сифской смолой"
	pcase = "сифской смоле"

/datum/reagent/acid/polyacid
	name = "Политриниковая кислота"
	description = "Крайне едкая субстанция."
	taste_description = "кислоты"
	rugender = "female"
	ncase = "политриниковая кислота"
	gcase = "политриниковой кислоты"
	dcase = "политриниковой кислоте"
	acase = "политриниковую кислоту"
	icase = "политриниковой кислотой"
	pcase = "политриниковой кислоте"

/datum/reagent/acid/digestive
	name = "Желудочный сок"
	description = "Некая желудочная кислота."
	taste_description = "блевотины"
	rugender = "male"
	ncase = "желудочный сок"
	gcase = "желудочного сока"
	dcase = "желудочному соку"
	acase = "желудочный сок"
	icase = "желудочным соком"
	pcase = "желудочном соке"

/datum/reagent/thermite/venom
	name = "Пиротоксин"
	description = "Соединение органического происхождения, способное расплавить сталь и другие металлы подобно термиту."
	taste_description = "сладкого мела"
	rugender = "male"
	ncase = "пиротоксин"
	gcase = "пиротоксина"
	dcase = "пиротоксину"
	acase = "пиротоксин"
	icase = "пиротоксином"
	pcase = "пиротоксине"

/datum/reagent/condensedcapsaicin/venom
	name = "Ирритант"
	description = "Биологическое соединение, сравнимое с перцовкой, однако более жестокое, так как способно просачиваться в кровеносные сосуды."
	taste_description = "огня"
	rugender = "male"
	ncase = "ирритант"
	gcase = "ирританта"
	dcase = "ирританту"
	acase = "ирритант"
	icase = "ирритантом"
	pcase = "ирританте"

/datum/reagent/lexorin
	name = "Лексорин"
	description = "Лексорин временно приостанавливает дыхательную систему. Может вызвать повреждения тканей."
	taste_description = "кислоты"
	rugender = "male"
	ncase = "лексорин"
	gcase = "лексорина"
	dcase = "лексорину"
	acase = "лексорин"
	icase = "лексорином"
	pcase = "лексорине"

/datum/reagent/mutagen
	name = "Нестабильный мутаген"
	description = "Может привести к непредсказуемым мутациям. Хранить в недоступном для детей месте."
	taste_description = "слизи"
	rugender = "male"
	ncase = "нестабильный мутаген"
	gcase = "нестабильного мутагена"
	dcase = "нестабильному мутагену"
	acase = "нестабильный мутаген"
	icase = "нестабильным мутагеном"
	pcase = "нестабильном мутагене"

/datum/reagent/slimejelly
	name = "Слизневое желе"
	description = "Склизкая полужидкость, выделяемая одной и самых опасных во вселенной форм жизни."
	taste_description = "слизи"
	rugender = "neuter"
	ncase = "слизневое желе"
	gcase = "слизневого желе"
	dcase = "слизневому желе"
	acase = "слизневое желе"
	icase = "слизневым желе"
	pcase = "слизневом желе"

/datum/reagent/soporific
	name = "Снотворное"
	description = "Эффективный препарат, применяемый против бессонницы."
	taste_description = "чего-то горького"
	rugender = "neuter"
	ncase = "снотворное"
	gcase = "снотворного"
	dcase = "снотворному"
	acase = "снотворное"
	icase = "снотворным"
	pcase = "снотворном"

/datum/reagent/chloralhydrate
	name = "Хлоральгидрат"
	description = "Сильное седативное средство."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "хлоральгидрат"
	gcase = "хлоральгидрата"
	dcase = "хлоральгидрату"
	acase = "хлоральгидрат"
	icase = "хлоральгидратом"
	pcase = "хлоральгидрате"

/datum/reagent/chloralhydrate/beer2
	name = "Пиво"
	description = "Алкогольный напиток из солода, хмеля, дрожжей и воды. Похоже, ферментация прошла не до конца."
	taste_description = "пива"
	glass_name = "Пиво"
	glass_desc = "Холодная кружка пива."
	rugender = "neuter"
	ncase = "пиво"
	gcase = "пива"
	dcase = "пиву"
	acase = "пиво"
	icase = "пивом"
	pcase = "пиве"
	glass_rugender = "neuter"
	glass_ncase = "пиво"
	glass_gcase = "пива"
	glass_dcase = "пиву"
	glass_acase = "пиво"
	glass_icase = "пивом"
	glass_pcase = "пиве"

/datum/reagent/space_drugs
	name = "Космические наркотики"
	description = "Незаконный препарат, используемый в качестве наркотиков."
	taste_description = "чего-то горького"
	rugender = "plural"
	ncase = "космические наркотики"
	gcase = "космических наркотиков"
	dcase = "космическим наркотикам"
	acase = "космические наркотики"
	icase = "космическими наркотиками"
	pcase = "космических наркотиках"

/datum/reagent/serotrotium
	name = "Серотротий"
	description = "Химическое соединение, способствующее выработке серотононина."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "серотротий "
	gcase = "серотротия"
	dcase = "серотротию"
	acase = "серотротий "
	icase = "серотротием"
	pcase = "серотротии"

/datum/reagent/serotrotium/venom
	name = "Серотропный яд"
	description = "Химическое соединение, способствующее выработке серотононина. Это соединение произведено органическим образом, в следствие чего является токсичным."
	taste_description = "горького мела"
	rugender = "male"
	ncase = "серотропный яд"
	gcase = "серотропного яда"
	dcase = "серотропному яду"
	acase = "серотропный яд"
	icase = "серотропным ядом"
	pcase = "серотропном яде"

/datum/reagent/cryptobiolin
	name = "Криптобиолин"
	description = "Криптобиолин вызывает запутанность и головокружение."
	taste_description = "кислоты"
	rugender = "male"
	ncase = "криптобиолин"
	gcase = "криптобиолина"
	dcase = "криптобиолину"
	acase = "криптобиолин"
	icase = "криптобиолином"
	pcase = "криптобиолине"

/datum/reagent/impedrezene
	name = "Импедрезин"
	description = "Наркотическое вещество, затормаживающее работу мозговых клеток."
	taste_description = "онемения"
	rugender = "male"
	ncase = "импедрезин"
	gcase = "импедрезина"
	dcase = "импедрезину"
	acase = "импедрезин"
	icase = "импедрезином"
	pcase = "импедрезине"

/datum/reagent/mindbreaker
	name = "Мозголом"
	description = "Мощный галлюциноген, способный привести к летальному исходу."
	taste_description = "кислоты"
	rugender = "male"
	ncase = "мозголом"
	gcase = "мозголома"
	dcase = "мозголому"
	acase = "мозголом"
	icase = "мозголомом"
	pcase = "мозголоме"

/datum/reagent/psilocybin
	name = "Псилоцибин"
	description = "Сильное психотропное вещество, содержащееся в определённом виде грибов."
	taste_description = "грибов"
	rugender = "male"
	ncase = "псилоцибин"
	gcase = "псилоцибина"
	dcase = "псилоцибину"
	acase = "псилоцибин"
	icase = "псилоцибином"
	pcase = "псилоцибине"

/datum/reagent/nicotine
	name = "Никотин"
	description = "Вещество, содержащееся в табаке и вызывающее привыкание."
	taste_description = "чего-то горького"
	rugender = "male"
	ncase = "никотин"
	gcase = "никотина"
	dcase = "никотину"
	acase = "никотин"
	icase = "никотином"
	pcase = "никотине"

/datum/reagent/talum_quem
	name = "Талум-кем"
	description = "Галлюциноген, изобретённый кастой Талум-катиш."
	taste_description = "жевательной резинки"
	rugender = "male"
	ncase = "талум-кем"
	gcase = "талум-кема"
	dcase = "талум-кему"
	acase = "талум-кем"
	icase = "талум-кемом"
	pcase = "талум-кеме"

/datum/reagent/slimetoxin
	name = "Мутационный токсин"
	description = "Вредоносный токсин, выделяемый слизнями."
	taste_description = "слизи"
	rugender = "male"
	ncase = "мутационный токсин"
	gcase = "мутационного токсина"
	dcase = "мутационному токсину"
	acase = "мутационный токсин"
	icase = "мутационным токсином"
	pcase = "мутационном токсине"

/datum/reagent/aslimetoxin
	name = "Токсин послушания"
	description = "Вредоносный токсин, выделяемый слизнями."
	taste_description = "слизи"
	rugender = "male"
	ncase = "токсин послушания"
	gcase = "токсина послушания"
	dcase = "токсину послушания"
	acase = "токсин послушания"
	icase = "токсином послушания"
	pcase = "токсине послушания"

/datum/reagent/shredding_nanites
	name = "Восстанавливающие наниты"
	description = "Миниатюрные медицинские наноботы, быстро и эффективно восстанавливающие повреждения в организме. Эти наниты, похоже, дефективны."
	taste_description = "металла"
	rugender = "plural"
	ncase = "восстанавливающие наниты"
	gcase = "восстанавливающих нанитов"
	dcase = "восстанавливающим нанитам"
	acase = "восстанавливающие наниты"
	icase = "восстанавливающими нанитами"
	pcase = "восстанавливающих нанитах"

/datum/reagent/irradiated_nanites
	name = "Восстанавливающие наниты"
	description = "Миниатюрные медицинские наноботы, быстро и эффективно восстанавливающие повреждения в организме. Эти наниты, похоже, дефективны."
	taste_description = "металла"
	rugender = "plural"
	ncase = "восстанавливающие наниты"
	gcase = "восстанавливающих нанитов"
	dcase = "восстанавливающим нанитам"
	acase = "восстанавливающие наниты"
	icase = "восстанавливающими нанитами"
	pcase = "восстанавливающих нанитах"

/datum/reagent/neurophage_nanites
	name = "Восстанавливающие наниты"
	description = "Миниатюрные медицинские наноботы, быстро и эффективно восстанавливающие повреждения в организме. Этот рой кажется полностью враждебным."
	taste_description = "металла"
	rugender = "plural"
	ncase = "восстанавливающие наниты"
	gcase = "восстанавливающих нанитов"
	dcase = "восстанавливающим нанитам"
	acase = "восстанавливающие наниты"
	icase = "восстанавливающими нанитами"
	pcase = "восстанавливающих нанитах"

//Chemistry-Reagents-Vore_vr.dm

/datum/reagent/macrocillin
	name = "Макроциллин"
	description = "Жёлтая светящаяся жидкость."
	rugender = "male"
	ncase = "макроциллин"
	gcase = "макроциллина"
	dcase = "макроциллину"
	acase = "макроциллин"
	icase = "макроциллином"
	pcase = "макроциллине"

/datum/reagent/microcillin
	name = "Микроциллин"
	description = "Фиолетовая жидкость."
	rugender = "male"
	ncase = "микроциллин"
	gcase = "микроциллина"
	dcase = "микроциллину"
	acase = "микроциллин"
	icase = "микроциллином"
	pcase = "микроциллине"

/datum/reagent/normalcillin
	name = "Нормалциллин"
	description = "Прозрачная голубоватая жидкость."
	rugender = "male"
	ncase = "нормалциллин"
	gcase = "нормалциллина"
	dcase = "нормалциллину"
	acase = "нормалциллин"
	icase = "нормалциллином"
	pcase = "нормалциллине"

/datum/reagent/sizeoxadone
	name = "Размероксадон"
	description = "Летучая жидкость, используемая в качестве основы для остальных препаратов, влияющих на размер. В чистом виде может вызвать головокружение."
	rugender = "male"
	ncase = "размероксадон"
	gcase = "размероксадона"
	dcase = "размероксадону"
	acase = "размероксадон"
	icase = "размероксадоном"
	pcase = "размероксадоне"

/datum/reagent/ickypak
	name = "Бякопак"
	description = "Зелёная жидкость, обладающая противным запахом и способная вызвать сокращения мышц, чтобы извлечь проглоченные по ошибке вещи."
	rugender = "male"
	ncase = "бякопак"
	gcase = "бякопака"
	dcase = "бякопаку"
	acase = "бякопак"
	icase = "бякопаком"
	pcase = "бякопаке"

/datum/reagent/unsorbitol
	name = "Антиглот"
	description = "Розовая жидкость, способная вызвать гетерогенное разделение сред на клеточном уровне."
	rugender = "male"
	ncase = "антиглот"
	gcase = "антиглота"
	dcase = "антиглоту"
	acase = "антиглот"
	icase = "антиглотом"
	pcase = "антиглоте"

/datum/reagent/grubshock
	name = "200 В"
	description = "Жидкость, мгновенно передающая удар электричеством, при этом растворяясь."
	rugender = "plural"
	ncase = "200 В"
	gcase = "200 В"
	dcase = "200 В"
	acase = "200 В"
	icase = "200 В"
	pcase = "200 В"