/obj/item/weapon/coin
	name = "Монетка"
	desc = "Обыкновенная монетка, которую можно подбросить."
	rugender = "female"
	ncase = "монетка"
	gcase = "монетки"
	dcase = "монетке"
	acase = "монетку"
	icase = "монеткой"
	pcase = "монетке"

/obj/item/weapon/coin/gold
	name = "Золотая монетка"
	rugender = "female"
	ncase = "золотая монетка"
	gcase = "золотой монетки"
	dcase = "золотой монетке"
	acase = "золотую монетку"
	icase = "золотой монеткой"
	pcase = "золотой монетке"

/obj/item/weapon/coin/silver
	name = "Серебряная монетка"
	rugender = "female"
	ncase = "серебряная монетка"
	gcase = "серебряной монетки"
	dcase = "серебряной монетке"
	acase = "серебряную монетку"
	icase = "серебряной монеткой"
	pcase = "серебряной монетке"

/obj/item/weapon/coin/diamond
	name = "Бриллиантовая монетка"
	rugender = "female"
	ncase = "бриллиантовая монетка"
	gcase = "бриллиантовой монетки"
	dcase = "бриллиантовой монетке"
	acase = "бриллиантовую монетку"
	icase = "бриллиантовой монеткой"
	pcase = "бриллиантовой монетке"

/obj/item/weapon/coin/iron
	name = "Железная монетка"
	rugender = "female"
	ncase = "железная монетка"
	gcase = "железной монетки"
	dcase = "железной монетке"
	acase = "железную монетку"
	icase = "железной монеткой"
	pcase = "железной монетке"

/obj/item/weapon/coin/phoron
	name = "Фороновая монетка"
	rugender = "female"
	ncase = "фороновая монетка"
	gcase = "фороновой монетки"
	dcase = "фороновой монетке"
	acase = "фороновую монетку"
	icase = "фороновой монеткой"
	pcase = "фороновой монетке"

/obj/item/weapon/coin/uranium
	name = "Урановая монетка"
	rugender = "female"
	ncase = "урановая монетка"
	gcase = "урановой монетки"
	dcase = "урановой монетке"
	acase = "урановую монетку"
	icase = "урановой монеткой"
	pcase = "урановой монетке"

/obj/item/weapon/coin/platinum
	name = "Платиновая монетка"
	rugender = "female"
	ncase = "платиновая монетка"
	gcase = "платиновой монетки"
	dcase = "платиновой монетке"
	acase = "платиновую монетку"
	icase = "платиновой монеткой"
	pcase = "платиновой монетке"
